### ISSUE TITLE
Bug with php7.4 : I can't use at all

### ISSUE THREAD

**Issue by mrsolarius** [radenvodka/Recsech#18]
**Describe the bug**
When I try to just start command nothing works I have no return...
And when I try with debug mode I have this return :
```php
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Sdata has a deprecated constructor in /home/mrsolarius/tools/Recsech/tools/sdata-modules.php on line 8
PHP Warning:  mkdir(): File exists in /home/mrsolarius/tools/Recsech/tools/sdata-modules.php on line 56
PHP Fatal error:  Uncaught Error: Call to undefined function curl_multi_init() in /home/mrsolarius/tools/Recsech/tools/sdata-modules.php:58
Stack trace:
#0 /home/mrsolarius/tools/Recsech/tools/sdata-modules.php(181): Sdata->sdata()
#1 /home/mrsolarius/tools/Recsech/Recsech.php(17): require_once('/home/louis/too...')
#2 {main}
  thrown in /home/mrsolarius/tools/Recsech/tools/sdata-modules.php on line 58
```

**To Reproduce**
1. Have php7.4-cli
2. Use `chmod -R u+x $path_to_recsecn$`
3. Do `php Recsech.php` in folder 
4. Nothing show
5. Do `php Recsech.php debug` to see error 

**Expected behavior**
Just have the title display like your screen ^^ 

**Desktop (please complete the following information):**
 - Kubuntu 20.04
 - PHP CLI 7.4

**Additional context**
I have try to start file with all 777 right but nothing have change.

**Comment by mrsolarius** [comment]
Sorry I have forgot to install `php-curl`
